services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - ../coach/.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  springbootapp:
    build:
      context: ../coach
      dockerfile: Dockerfile
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../coach/.env

volumes:
  mysql_data:
