services:
  redis:
    image: redis:latest
    container_name: coach-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    env_file:
      - ../Coach/.env

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672" # RabbitMQ Admin Panel
    env_file:
      - ../Coach/.env

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ../Coach/.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  springbootapp:
    build:
      context: ../Coach
      dockerfile: Dockerfile
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../Coach/.env

volumes:
  pg_data:
